### ISSUE TITLE
Get rid of image sizes from images

### ISSUE THREAD

**Issue by D-Mielewczyk** [D-Mielewczyk/pawel-jumper#1]
In assets, all of the images have their size in the name. We don't need that and it needs to be refactored.

![image](https://github.com/D-Mielewczyk/pawel-jumper/assets/55713797/e3169bef-3264-4c7e-a710-8e631acf3873)

**Comment by wojtekszamocki** [comment]
It's better to leave it as it is - you dont need to check heigth and width of images when opening them
